[FEAT] updates
cirbuk/litedash pull request #7
Opened 2021-04-01 18:47 UTC by abhijith-vijayan

Signed-off-by: Abhijith Vijayan [KUBRIC] <78354201+abhijith-vijayan@users.noreply.github.com>

- gitignored IDE files
- bump typescript to v4.2.3
- added `isNullOrUndefined()` method
- use type-guards for `isString`, `isNull`, `isUndefined` methods
- and other minor fixes

2021-04-02 03:09 UTC, ophinjay commented
@abhijith-vijayan 
 - Remove yarn.lock
 - Add latest package-lock.json
 - Update `version` to 1.0.0 in package.json

2021-04-02 03:09 UTC, ophinjay requested changes
@abhijith-vijayan 

 - Remove yarn.lock
 - Add latest package-lock.json
 - Update version to 1.0.0 in package.json

2021-04-02 14:55 UTC, abhijith-vijayan commented
@ophinjay done ^^

2021-04-08 07:48 UTC, ophinjay approved these changes

2021-04-08 07:49 UTC, merged